# Generated by Django 5.1.3 on 2024-12-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0002_remove_copetencias_entregado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copetencias',
            old_name='fechaDeCopetencia',
            new_name='fecha',
        ),
    ]
