# Generated by Django 5.1.3 on 2024-12-26 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0005_inscripcion_detalles_profesor_detallesprof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='detalles',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='detallesProf',
        ),
    ]
