# Generated by Django 5.1.3 on 2024-12-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0006_remove_inscripcion_detalles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='detalle',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
