# Generated by Django 5.1.3 on 2024-12-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0007_profesor_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='detalle',
            field=models.TextField(null=True),
        ),
    ]
