# Generated by Django 5.1.3 on 2024-12-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClub', '0008_alter_profesor_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='copetencias',
            name='detalle',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='detalle',
            field=models.TextField(null=True),
        ),
    ]
